# Railway Configuration
# This file configures Railway deployment for RT-Lakehouse

[build]
builder = "dockerfile"
dockerfilePath = "rt-lakehouse/Dockerfile.railway"

[env]
# API Configuration
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

# CORS for Railway subdomain
CORS_ORIGINS = '["https://*.railway.app", "https://*.up.railway.app"]'

# Simplified configuration for Railway
ENABLE_METRICS = "true"
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# Feature flags for Railway demo
ENABLE_TIME_TRAVEL = "false"
ENABLE_ML_FEATURES = "true"
ENABLE_VECTOR_SEARCH = "false"
ENABLE_ALERTS = "true"
