# Railway Configuration
# This file configures Railway deployment for RT-Lakehouse

[build]
builder = "dockerfile"
dockerfilePath = "rt-lakehouse/Dockerfile.railway"

[deploy]
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
# Default to API service
SERVICE_NAME = "api"

# Railway will set PORT automatically
# PORT = 8000

# API Configuration
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"

# CORS for Railway subdomain
CORS_ORIGINS = '["https://*.railway.app", "https://*.up.railway.app"]'

# Simplified configuration for Railway
ENABLE_METRICS = "true"
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# Feature flags
ENABLE_TIME_TRAVEL = "false"  # Disable for Railway demo
ENABLE_ML_FEATURES = "true"
ENABLE_VECTOR_SEARCH = "false"  # Disable Qdrant for Railway demo
ENABLE_ALERTS = "true"
